eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hello